### ISSUE TITLE
Just a Typo

### ISSUE THREAD

**Issue by 100amps** [arrowtype/fonttools-intro#5]
Is this irony or just an unlucky coincidence?

"Additionally, if you spot something here that is **innacurate** or if you have questions, please file an [issue](https://github.com/arrowtype/fonttools-intro/issues) or [pull request](https://github.com/arrowtype/fonttools-intro/pulls) in this repo to help myself & others learn!"

spelling: inaccurate

**Comment by arrowtype** [comment]
Oh, lol, good catch!

**Comment by arrowtype** [comment]
Thanks for letting me know! Fixed, I think.
